"""somenewupdatePRODUCT

Revision ID: 2848cd84d0b5
Revises: fc89adcabdf9
Create Date: 2024-06-06 20:27:52.708350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2848cd84d0b5'
down_revision: Union[str, None] = 'fc89adcabdf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
